name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or any branch where you trigger this action

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up GitHub Actions Bot Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run F5 Info Script
        env:
          BIGIP_USERNAME: ${{ secrets.BIGIP_USERNAME }}
          BIGIP_PASSWORD: ${{ secrets.BIGIP_PASSWORD }}
        run: |
          python3 f5_info_script.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin ${GITHUB_REF#refs/heads/} --rebase
          git add README.md device_*.md virtual_servers_*.csv pool_members_*.csv problematic_virtual_servers.csv
          git commit -m "Update F5 reports for GitHub Pages [skip ci]" || echo "No changes to commit"
          git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${GITHUB_REF#refs/heads/}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Change to the branch you've set up for GitHub Pages
          publish_dir: ./  # Adjust this to point to your generated content (e.g., 'docs/' if you’re using that)
